name: 'Trivy PR Decorator'
description: 'Parse Trivy vulnerability scan results and post formatted comments to pull requests. Supports workflow_run pattern for fork PRs and Dependabot.'
author: 'Katanox'

inputs:
  results-file:
    description: 'Path to the Trivy JSON results file'
    required: true
  github-token:
    description: 'GitHub token for API authentication'
    required: true
  max-table-rows:
    description: 'Maximum number of rows to display in the vulnerability details table'
    required: false
    default: '20'
  event-file:
    description: 'Path to GitHub event file (for workflow_run support). Defaults to GITHUB_EVENT_PATH'
    required: false
    default: ''
  event-name:
    description: 'GitHub event name (for workflow_run support). Defaults to GITHUB_EVENT_NAME'
    required: false
    default: ''
  artifact-name:
    description: 'Name of artifact containing test results (for workflow_run support)'
    required: false
    default: ''
  event-artifact-name:
    description: 'Name of artifact containing event file (for workflow_run support)'
    required: false
    default: ''
  sha:
    description: 'Commit SHA to use for PR lookup (optional, auto-detected if not provided)'
    required: false
    default: ''

outputs:
  total-vulnerabilities:
    description: 'Total number of vulnerabilities found'
  critical-count:
    description: 'Number of CRITICAL vulnerabilities'
  high-count:
    description: 'Number of HIGH vulnerabilities'
  medium-count:
    description: 'Number of MEDIUM vulnerabilities'
  low-count:
    description: 'Number of LOW vulnerabilities'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'shield'
  color: 'red'
